# necessary to use Jekyll with GitHub pages
repository: callumhackett/callumhackett.github.io

# the following are invariant across the site
author: Callum Hackett
site_name: Callum Hackett
favicon: /assets/images/hand.jpg
twitter: >-
  @callumjhackett

# the following are defaults that can be overridden on individual pages
type: website
description: I work with languages, some organic ğŸ§¬ and some artificial ğŸ¤–
social_image: /assets/images/hand.jpg
social_image_alt: Callum Hackett

# these third party plugins enable an ATOM feed and a sitemap
plugins:
  - jekyll-feed
  - jekyll-sitemap
